name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet==0.28.3 requests

      - name: 打包 APK
        run: flet build apk

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk